spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itutor?useSSL=false
    username: root
    password: 699685
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080