spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.123.133:3306/itutor?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: USST
    password: USST1906
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
server:
  port: 8080